spring.jpa:
  database: postgresql
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

spring.datasource:
  hikari:
    maximum-pool-size: 4
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: yoonho.sns-application-2022.secret_key
  # 30 Days
  token-expired-time-ms: 2592000000